/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MandirayanRouteImport } from './routes/mandirayan'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VasudhayanRouteImport } from './routes/vasudhayan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MandirayanRoute = MandirayanRouteImport.update({
  id: '/mandirayan',
  path: '/mandirayan',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VasudhayanRoute = VasudhayanRouteImport.update({
  id: '/vasudhayan',
  path: '/vasudhayan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mandirayan': typeof MandirayanRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/vasudhayan': typeof VasudhayanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mandirayan': typeof MandirayanRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/vasudhayan': typeof VasudhayanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mandirayan': typeof MandirayanRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/vasudhayan': typeof VasudhayanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mandirayan' | '/privacy' | '/terms' | '/vasudhayan'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mandirayan' | '/privacy' | '/terms' | '/vasudhayan'
  id: '__root__' | '/' | '/mandirayan' | '/privacy' | '/terms' | '/vasudhayan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MandirayanRoute: typeof MandirayanRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  VasudhayanRoute: typeof VasudhayanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mandirayan': {
      id: '/mandirayan'
      path: '/mandirayan'
      fullPath: '/mandirayan'
      preLoaderRoute: typeof MandirayanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vasudhayan': {
      id: '/vasudhayan'
      path: '/vasudhayan'
      fullPath: '/vasudhayan'
      preLoaderRoute: typeof VasudhayanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MandirayanRoute: MandirayanRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  VasudhayanRoute: VasudhayanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
